# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  # Ensure Next.js uses the correct Node version
  NODE_VERSION = "18"
  # Exclude build output from secrets scanning - scan source files only
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,netlify/**,_next/**,*.js.map"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Important: Make environment variables available to functions
[context.production.environment]
  # These will be merged with UI-configured variables

[context.deploy-preview.environment]
  # Preview deployments use the same variables

[context.branch-deploy.environment]
  # Branch deployments use the same variables

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# PWA manifest headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

# Service worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache, must-revalidate"
    Service-Worker-Allowed = "/"

# Icon headers
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

# API route configuration - ensure they run as functions
[[headers]]
  for = "/api/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

# Redirects
[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 301

[[redirects]]
  from = "/judge/*"
  to = "/judges/:splat"
  status = 301

# Note: PWA offline fallback removed - Next.js handles routing

# Important: Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variable configuration hints
# Set these in Netlify UI under Site Settings → Environment Variables:
# 
# Required for database connection:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY
# 
# Required for authentication:
# - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
# - CLERK_SECRET_KEY
# 
# Required for data sync:
# - COURTLISTENER_API_KEY
# 
# Required for site configuration:
# - NEXT_PUBLIC_SITE_URL
# 
# Optional but recommended:
# - CRON_SECRET (for scheduled functions)
# - UPSTASH_REDIS_REST_URL (for rate limiting)
# - UPSTASH_REDIS_REST_TOKEN (for rate limiting)
# - SENTRY_DSN (for error tracking)