# Netlify Configuration for JudgeFinder Platform
[build]
  # Force installation of all dependencies including devDependencies
  command = "npm ci --production=false && npm run build"
  publish = ".next"

[build.environment]
  # Use Node 20 LTS for better compatibility
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  # Ensure all dependencies are installed
  NPM_FLAGS = "--production=false"
  # Enable Next.js build cache
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  # Disable Neon extension to prevent @netlify/blobs version conflict
  NETLIFY_USE_NEON = "false"
  
  # Secrets Scanning Configuration - Expanded exclusions to prevent false positives
  # Skip scanning in all script directories, documentation, and test files
  SECRETS_SCAN_OMIT_PATHS = "scripts/**,*.example,*.md,*.txt,docs/**,reports/**,*.json,test/**,tests/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts"
  # Exclude all environment variable names and build-time variables
  SECRETS_SCAN_OMIT_KEYS = "NODE_VERSION,NEXT_TELEMETRY_DISABLED,NPM_FLAGS,NETLIFY_*,NEXT_PUBLIC_*,BUILD_*,CI,DEPLOY_*,REVIEW_ID,SITE_*,URL,DEPLOY_URL,DEPLOY_PRIME_URL,CACHED_COMMIT_REF,COMMIT_REF,PULL_REQUEST,INCOMING_HOOK_*,CONTEXT,BRANCH"
  # Prevent security scripts from running during build
  NETLIFY_BUILD = "true"

# Next.js Build Settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.clerk.com *.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' *.supabase.co *.clerk.com *.sentry.io *.courtlistener.com https://api.openai.com https://generativelanguage.googleapis.com;"

# Environment-specific configurations
[context.production]
  command = "npm ci --production=false && npm run build"
  
[context.deploy-preview]
  command = "npm ci --production=false && npm run build"

[context.branch-deploy]
  command = "npm ci --production=false && npm run build"

# Edge Functions directory (commented out until functions are created)
# [[edge_functions]]
#   path = "/api/*"
#   function = "api-handler"