# Netlify Configuration for JudgeFinder Platform
[build]
  # Build command - using legacy-peer-deps to handle version conflicts
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
  # Disable telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build environment flag
  NETLIFY_BUILD = "true"
  
  # Skip auth during build to prevent useContext errors
  SKIP_AUTH_BUILD = "true"
  
  # Skip automatic Next.js plugin installation to avoid @netlify/blobs error
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_USE_YARN = "false"
  
  # Skip all extensions and plugins to prevent version conflicts
  NETLIFY_SKIP_FUNCTIONS_CACHE = "true"
  NETLIFY_SKIP_PLUGIN_INSTALLATION = "true"
  
  # Secrets scanning configuration - prevent false positives
  # Include build output directories and configuration files
  # Exclude all build artifacts, documentation, and non-code files
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,scripts/**,*.example,*.md,*.txt,docs/**,reports/**,*.json,test/**,tests/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,lib/seo/**,lib/utils/**,next.config.js,public/**,data/**,lib/security/**,supabase/**,netlify.toml,components/seo/**,node_modules/**,.env.example,package*.json,tsconfig.json,*.config.js,*.config.ts,.gitignore,.eslintrc*,validation-reports/**,la-county-data/**,monitoring/**"
  
  # Include domain patterns, URL patterns, and common non-secret strings
  # These are public values or configuration names, not actual secrets
  SECRETS_SCAN_OMIT_KEYS = "NODE_VERSION,NEXT_TELEMETRY_DISABLED,NPM_FLAGS,NETLIFY_*,NEXT_PUBLIC_*,BUILD_*,CI,DEPLOY_*,REVIEW_ID,SITE_*,URL,DEPLOY_URL,DEPLOY_PRIME_URL,CACHED_COMMIT_REF,COMMIT_REF,PULL_REQUEST,INCOMING_HOOK_*,CONTEXT,BRANCH,judgefinder.io,https://judgefinder.io,http://judgefinder.io,*.judgefinder.io,JudgeFinder Platform,JudgeFinder.io,localhost,supabase.co,*.supabase.co,xstlnicbnzdxlgfiewmg"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.clerk.com *.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' *.supabase.co *.clerk.com *.sentry.io *.courtlistener.com https://api.openai.com https://generativelanguage.googleapis.com;"
