# ============================================
# Netlify Configuration - JudgeFinder Platform
# ============================================
# Production deployment configuration for Netlify
# See: https://docs.netlify.com/configure-builds/file-based-configuration/
# ============================================

[build]
  command = "npm run build"
  # NOTE: Do NOT set 'publish' when using @netlify/plugin-nextjs
  # The plugin automatically manages the output directory for Next.js SSR
  # publish = ".next"  # Commented out - managed by Next.js plugin
  functions = "netlify/functions"

[build.environment]
  # Node.js and Build Configuration
  NODE_VERSION = "20"  # Match package.json requirement (^20)
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

  # IMPORTANT: Set ENCRYPTION_KEY in Netlify UI
  # Navigate to: Site settings > Environment variables > Add variable
  # Required for secure data encryption in production

  # Public Environment Variables (safe for client-side, NEXT_PUBLIC_ prefix)
  NEXT_PUBLIC_APP_NAME = "JudgeFinder Platform"
  NEXT_PUBLIC_APP_URL = "https://judgefinder.io"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/dashboard"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/welcome"

  # Build Optimizations
  NEXT_TELEMETRY_DISABLED = "1"

  # Secrets Scanning Configuration
  # Exclude build artifacts and public env vars from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,.git/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,NEXT_PUBLIC_CLERK_SIGN_UP_URL,NEXT_PUBLIC_APP_NAME,NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,NEXT_PUBLIC_CLERK_SIGN_IN_URL,NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_APP_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

# ============================================
# Context-Specific Configurations
# ============================================

# Production Context
[context.production]
  command = "npm run build:production"
  [context.production.environment]
    NODE_ENV = "production"

# Deploy Preview Context (PR previews)
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

# Branch Deploy Context
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Redirect rules for SEO
[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/sitemap-index.xml"
  to = "/sitemap.xml"
  status = 301

# Headers for security and SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

# ============================================
# Serverless Functions Configuration
# ============================================

[functions]
  # Function bundler and optimization
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "@google/generative-ai", "sharp"]

  # Function timeouts (max 26 seconds for standard functions)
  # Background functions can run up to 15 minutes
  [functions.timeout]
    default = 10  # 10 seconds default
    api = 26      # API endpoints can use full 26 seconds

# Scheduled Functions
[functions."submit-sitemap"]
  schedule = "@weekly"

# ============================================
# Post-Processing & Optimization
# ============================================

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# ============================================
# Plugin Configuration
# ============================================

[[plugins]]
  package = "@netlify/plugin-nextjs"
