# Netlify Configuration for JudgeFinder Platform
[build]
  # Build command
  command = "npm ci --production=false && npm run build"
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
  # Disable telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build environment flag
  NETLIFY_BUILD = "true"
  
  # Skip automatic Next.js plugin installation to avoid @netlify/blobs error
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_USE_YARN = "false"
  
  # Secrets scanning configuration - prevent false positives
  SECRETS_SCAN_OMIT_PATHS = "scripts/**,*.example,*.md,*.txt,docs/**,reports/**,*.json,test/**,tests/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts"
  SECRETS_SCAN_OMIT_KEYS = "NODE_VERSION,NEXT_TELEMETRY_DISABLED,NPM_FLAGS,NETLIFY_*,NEXT_PUBLIC_*,BUILD_*,CI,DEPLOY_*,REVIEW_ID,SITE_*,URL,DEPLOY_URL,DEPLOY_PRIME_URL,CACHED_COMMIT_REF,COMMIT_REF,PULL_REQUEST,INCOMING_HOOK_*,CONTEXT,BRANCH"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.clerk.com *.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' *.supabase.co *.clerk.com *.sentry.io *.courtlistener.com https://api.openai.com https://generativelanguage.googleapis.com;"

# Netlify will auto-detect Next.js - no plugin needed
# This avoids the @netlify/blobs dependency issue