# Netlify configuration for JudgeFinder platform

[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect rules for SEO
[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/sitemap-index.xml"
  to = "/sitemap.xml"
  status = 301

# Headers for security and SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

# Scheduled functions configuration
[functions."submit-sitemap"]
  schedule = "@weekly"

# Edge function configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "@google/generative-ai"]

# Ignore false positive secret detection for Next.js public variables
# These variables are intentionally exposed to the client by Next.js design
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Configure Netlify to ignore NEXT_PUBLIC_ variables in secret scanning
# Note: Netlify may still warn about these, but they are safe to expose
[build.environment]
  # Public environment variables (safe for client-side)
  NEXT_PUBLIC_APP_NAME = "JudgeFinder Platform"
