# Netlify Configuration for JudgeFinder Platform
[build]
  # Build command - using legacy-peer-deps to handle version conflicts
  command = "npm ci --legacy-peer-deps && npm run build"
  # No publish directory needed for Next.js with Netlify plugin
  # The plugin handles the output automatically

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
  # Disable telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build environment flag
  NETLIFY_BUILD = "true"
  
  # Enable auth for production
  # SKIP_AUTH_BUILD is removed to allow Clerk to initialize properly
  
  # Enable Next.js plugin for proper routing
  NETLIFY_USE_YARN = "false"
  
  # Keep functions cache for better performance
  NETLIFY_SKIP_FUNCTIONS_CACHE = "false"
  
  # Secrets scanning configuration - prevent false positives
  # Include build output directories and configuration files
  # Exclude all build artifacts, documentation, and non-code files
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,scripts/**,*.example,*.md,*.txt,docs/**,reports/**,*.json,test/**,tests/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,lib/seo/**,lib/utils/**,next.config.js,public/**,data/**,lib/security/**,supabase/**,netlify.toml,components/seo/**,node_modules/**,.env.example,package*.json,tsconfig.json,*.config.js,*.config.ts,.gitignore,.eslintrc*,validation-reports/**,la-county-data/**,monitoring/**"
  
  # Include domain patterns, URL patterns, and common non-secret strings
  # These are public values or configuration names, not actual secrets
  SECRETS_SCAN_OMIT_KEYS = "NODE_VERSION,NEXT_TELEMETRY_DISABLED,NPM_FLAGS,NETLIFY_*,NEXT_PUBLIC_*,BUILD_*,CI,DEPLOY_*,REVIEW_ID,SITE_*,URL,DEPLOY_URL,DEPLOY_PRIME_URL,CACHED_COMMIT_REF,COMMIT_REF,PULL_REQUEST,INCOMING_HOOK_*,CONTEXT,BRANCH,judgefinder.io,https://judgefinder.io,http://judgefinder.io,*.judgefinder.io,JudgeFinder Platform,JudgeFinder.io,localhost,supabase.co,*.supabase.co,xstlnicbnzdxlgfiewmg"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.clerk.com https://*.clerk.accounts.dev https://clerk.shared.lcl.dev https://cdn.jsdelivr.net *.googleapis.com https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https: blob: https://img.clerk.com https://images.clerk.dev https://uploadthing.com; connect-src 'self' *.supabase.co wss://*.supabase.co https://*.clerk.com https://*.clerk.accounts.dev wss://*.clerk.accounts.dev https://clerk.shared.lcl.dev https://cdn.jsdelivr.net *.sentry.io *.courtlistener.com https://api.openai.com https://generativelanguage.googleapis.com https://challenges.cloudflare.com; frame-src 'self' https://*.clerk.com https://*.clerk.accounts.dev https://challenges.cloudflare.com;"
