#!/bin/bash

# ============================================
# Netlify Environment Variable Quick Fix
# ============================================
# This script helps identify which variables to remove from Netlify
# to fix the AWS Lambda 4KB limit error
# ============================================

echo "============================================"
echo "Netlify Environment Variable Fix Guide"
echo "============================================"
echo ""
echo "🚨 ERROR: Your environment variables exceed AWS Lambda's 4KB limit"
echo ""
echo "📋 You need to DELETE these 13 variables from Netlify UI:"
echo ""
echo "Go to: https://app.netlify.com/sites/judgefinder/settings/deploys"
echo "Navigate to: Site Settings → Environment Variables → Edit variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ DELETE - Build Config (already in netlify.toml)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1.  SECRETS_SCAN_OMIT_KEYS    (~2KB - BIGGEST BLOAT)"
echo "2.  SECRETS_SCAN_OMIT_PATHS   (~1.5KB - SECOND BIGGEST)"
echo "3.  NODE_ENV"
echo "4.  NODE_VERSION"
echo "5.  NPM_FLAGS"
echo "6.  CI"
echo "7.  NEXT_TELEMETRY_DISABLED"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ DELETE - Duplicates"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "8.  SUPABASE_ANON_KEY         (use NEXT_PUBLIC_SUPABASE_ANON_KEY)"
echo "9.  PGPASSWORD                (already in SUPABASE_DATABASE_URL)"
echo "10. GOOGLE_GENERATIVE_AI_API_KEY  (use GOOGLE_AI_API_KEY instead)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ DELETE - Deprecated Stripe (not used)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "11. STRIPE_PRICE_ADSPACE"
echo "12. STRIPE_PRICE_AD_SLOT"
echo "13. STRIPE_PRICE_PRO"
echo "14. STRIPE_PRICE_TEAM"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ KEEP - Required Variables (32 total)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Core:"
echo "  ✓ NEXT_PUBLIC_SUPABASE_URL"
echo "  ✓ NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "  ✓ SUPABASE_SERVICE_ROLE_KEY"
echo "  ✓ NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
echo ""
echo "Authentication:"
echo "  ✓ CLERK_SECRET_KEY"
echo "  ✓ SESSION_SECRET"
echo "  ✓ ENCRYPTION_KEY"
echo "  ✓ ADMIN_USER_IDS"
echo ""
echo "Database:"
echo "  ✓ SUPABASE_DATABASE_URL"
echo "  ✓ SUPABASE_JWT_SECRET"
echo ""
echo "Stripe:"
echo "  ✓ STRIPE_SECRET_KEY"
echo "  ✓ STRIPE_WEBHOOK_SECRET"
echo "  ✓ NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "  ✓ STRIPE_PRICE_MONTHLY"
echo "  ✓ STRIPE_PRICE_YEARLY"
echo ""
echo "External APIs:"
echo "  ✓ COURTLISTENER_API_KEY"
echo "  ✓ COURTLISTENER_WEBHOOK_VERIFY_TOKEN"
echo "  ✓ GOOGLE_AI_API_KEY       (NOT GOOGLE_GENERATIVE_AI_API_KEY)"
echo "  ✓ OPENAI_API_KEY"
echo ""
echo "Sync & Cron:"
echo "  ✓ SYNC_API_KEY"
echo "  ✓ CRON_SECRET"
echo ""
echo "Cache:"
echo "  ✓ UPSTASH_REDIS_REST_URL"
echo "  ✓ UPSTASH_REDIS_REST_TOKEN"
echo ""
echo "Public URLs (7 variables):"
echo "  ✓ NEXT_PUBLIC_APP_NAME"
echo "  ✓ NEXT_PUBLIC_APP_URL"
echo "  ✓ NEXT_PUBLIC_SITE_URL"
echo "  ✓ NEXT_PUBLIC_CLERK_SIGN_IN_URL"
echo "  ✓ NEXT_PUBLIC_CLERK_SIGN_UP_URL"
echo "  ✓ NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL"
echo "  ✓ NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL"
echo ""
echo "Optional:"
echo "  ✓ NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT"
echo "  ✓ NEXT_PUBLIC_ENABLE_ADS"
echo "  ✓ NEXT_PUBLIC_SENTRY_DSN"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 SIZE REDUCTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Before: 46 variables (~5KB)"
echo "After:  32 variables (~2KB)"
echo "Saved:  ~3KB ✅ Under AWS Lambda 4KB limit"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 AFTER DELETION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Save changes in Netlify UI"
echo "2. Trigger new deployment:"
echo "   - Click: Deploys → Trigger deploy → Deploy site"
echo "   - Or push empty commit: git commit --allow-empty -m 'trigger deploy'"
echo ""
echo "3. Monitor build at:"
echo "   https://app.netlify.com/sites/judgefinder/deploys"
echo ""
echo "Expected result: ✅ Deploy succeeds without Lambda size errors"
echo ""
echo "============================================"

